
@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(customer, "Клиент", "Клиент банка")
Person(back_office_person, "Сотрудник бэк-офиса")
Person(call_center_agents, "Оператор колл-центра")

System_Boundary(serviceBoundary, "Сервисы в контуре банка") {
  System(banking_services, "Сервис депозитов банка", "Работа с депозитами")
  System(abs, "АБС", "Автоматизированная банковская система")
  System(call_center, "Колл-центр", "CRM-платформа")
}


System_Ext(sms_operator, "Телеком оператор", "Оператор для отправки СМС")

Rel(call_center_agents, call_center, "Создание заявки на депозит")
Rel(back_office_person, abs, "Обработка заявок")
Rel(banking_services, call_center, "Уведомления о новых заявках и статусах")
Rel(banking_services, abs, "Передача заявок на обработку")
Rel(banking_services, sms_operator, "Отправка сведений для СМС")
Rel(sms_operator, customer, "Отправка СМС")

@enduml
